all:
  children:
    app_server:
      hosts:
        app_vm:
          ansible_host: 4.218.12.135
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/azure_sms_rsa
  vars:
    ansible_python_interpreter: /usr/bin/python3
